encyclopedia/urls.py
from django.urls import path

from . import views

#app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry_name>",views.call_get_entry,name="entry"),
    path("wiki/",views.show_entry,name="show_entry"),                #for search bar
    path("add/",views.add,name="add"),
    path("edit/<str:entry_name>",views.edit_page,name="edit"),
    path("random/",views.random_page,name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
#from django.urls import resolve
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django import forms


import markdown2
from . import util
import random




class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label="Entry Title")
    entry_body = forms.CharField(label="Entry Content",widget=forms.Textarea())


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def call_get_entry(request,entry_name):
    try:
        mhtml = markdown2.markdown(util.get_entry(entry_name))
    except TypeError:
        mhtml="<h1>Whoops! No such entry</h1>"

    return render(request, "encyclopedia/layout.html", {
        "entry":mhtml,
        "ename":entry_name,
        "editable":True
    })


def show_entry(request):
    entry_name=request.GET.get('q')
    entry_list = util.list_entries()
    print(entry_name)
    print(entry_list)
    result_list=[]
    for e in range(len(entry_list)):
        if entry_list[e].casefold().startswith(entry_name.casefold()):
            print("match found")
            result_list.append(entry_list[e])

    print(result_list)
    entry_exists=True
    try:
        mhtml = markdown2.markdown(util.get_entry(entry_name))
    except TypeError:
        entry_exists=False
        mhtml="<h1>Whoops! No such entry</h1>"

    if result_list == [] :
        return render(request, "encyclopedia/layout.html", {
        "entry":mhtml
    })
    if entry_exists:
        rd_url = "/wiki/"+entry_name
        print(rd_url)
        return redirect(rd_url)
    else:
        return render(request, "encyclopedia/index.html", {
        "entries": result_list
    })

    rd_url = "/wiki/"+entry_name
    print(rd_url)
    return redirect(rd_url)

def add(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        if form.is_valid():
            entry_title = form.cleaned_data["entry_title"]
            entry_body = form.cleaned_data["entry_body"]
            if entry_title in util.list_entries():
                return render(request, "encyclopedia/layout.html", {
                        "entry":"<h1>Sorry, Entry Already Exists!!!<h1>"
                        })
            
            util.save_entry(entry_title,entry_body)

            r_url = "/wiki/"+entry_title
            return HttpResponseRedirect(r_url)
        else:
            return render(request,"encyclopedia/layout.html",{
                "form" : form
            })

    return render(request,"encyclopedia/layout.html",{
        "form":NewEntryForm(),
    })


class EditForm(forms.Form):
    title = forms.CharField(label="Title",disabled=False)
    body = forms.CharField(label="Content",widget=forms.Textarea)


def edit_page(request,entry_name):
    if request.method == "POST":
        form = EditForm(request.POST)

        #if form.is_valid(): we are not validatiing
        entry_title = entry_name#form.cleaned_data["title"] no clean data availabe
        entry_body = form['body'].value()#form.cleaned_data["body"] no clean data available

        util.save_entry(entry_title,entry_body)

        r_url = "/wiki/"+entry_title
        return HttpResponseRedirect(r_url)

    return render(request,"encyclopedia/layout.html",{
        "form":None,
        "edit_form":True,
        "ename":entry_name,
        "ebody":util.get_entry(entry_name)
    })

def random_page(request):
    entries_list=util.list_entries()
    print(entries_list)
    r_entry = random.choice(entries_list)
    print("random item from list is: ", r_entry )

    rd_url="/wiki/"+r_entry
    return HttpResponseRedirect(rd_url)

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
           <a href="{% url 'entry' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div class="row">
      <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form action="{% url 'show_entry' %}" method="get">
          <input
            class="search"
            type="text"
            name="q"
            placeholder="Search Encyclopedia"
          />
        </form>
        <div>
          <a href="{% url 'index' %}">Home</a>
        </div>
        <div>
          <a href="{% url 'add' %}">Create New Page </a>
        </div>
        <div>
            <a href="{% url 'random' %}">
                Random Page
            </a>
        </div>
        {% if editable is True %}
        <div>
          <a href="/edit/{{ename}}">Edit This Page </a>
        </div>
        {% endif %} {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9">
        {% block body %} {{ entry|safe }} 
        
        {% if form is not None %}
        <h1>Create A New Page</h1>
        <form action="{% url 'add' %}" method="post">
          {% csrf_token %} 

          {{ form.non_field_errors }}
          <p>
          <div class="fieldWrapper">
              {{ form.entry_title.errors }}
              {{ form.entry_title.label_tag }}
              {{ form.entry_title }}
          </div>
        </p>
          <div class="fieldWrapper">
              {{ form.entry_body.errors }}
              <p>
                {{ form.entry_body.label_tag }}
              </p>
              <p>
                {{ form.entry_body }}
              </p>
          </div>
            <input type="submit" />
        </form>
        {% endif %} 

        {% if edit_form is not None %}
        <h1>Edit {{ename|safe}} Page</h1>
        <form action="{% url 'edit' ename %}" method="post">
          {% csrf_token %}
            <p>
                <label for="id_title">Title:</label>
                <input type="text" name="title" required id="id_title" value={{ename}} disabled />
            </p>

            <p>
                <label for="id_body">Content:</label>
            </p>
            <p>
                <textarea
                  name="body"
                  cols="40"
                  rows="10"
                  required
                  id="id_body"
                >
                {{ebody}}
              </textarea>
            </p>
            
          <input type="submit" />
        </form>
        {% endif %} {% endblock %}
      </div>
    </div>
  </body>
</html>